### ISSUE TITLE
Persist Array in React Native, empty string? -- can't repro

### ISSUE THREAD

**Issue by gHashTag** [agilgur5/mst-persist#29] opened 2021-05-07 10:39 UTC
Why if I add `mst-persist` all keys are kept except `finishArr` which becomes an empty string? 

Isn't it possible to store arrays in it?

```javascript
const Dice = types
.model('Dice', {
    startGame: types.boolean,
    count: types.number,
    players: types.number,
    message: types.string,
    multi: types.number,
    finishArr: types.array(types.boolean)
  })
  
const DiceStore = Dice.create({
  startGame: false,
  count: 6,
  players: 1,
  message: ' ',
  multi: 0,
  finishArr: [true, true, true, true, true, true]
})

persist('@DiceStore', DiceStore, {
  storage: AsyncStorage, // AsyncStorage for React-Native, localStorage for web
  jsonify: true, // Set to true if using AsyncStorage
  whitelist: ['startGame', 'count', 'players', 'message', 'multi', 'gamer', 'finishArr'] // only these keys will be persisted
})
```

**Comment by agilgur5** [comment] 2023-07-19 05:39
Sorry for not responding to this timely. My GitHub [status at the time](https://twitter.com/agilgur5/status/1488620710566191104?s=20) mentioned I was taking a break from OSS due to toxicity and abuse. Coming back now per my current status.

Getting to the question at hand, this _might_ be due to #5. Currently data from `create` is actually not persisted. A way to check against #5 would be to make a change to `DiceStore.finishArr` (e.g. via an `action`) and see if _that_ change is later persisted. If a change is persisted, then this would just be a duplicate of #5. If it isn't persisted, well then this could be a bug.

I need to make a reproduction environment for this package as currently behaviors in issues can be really hard to reproduce 😕

**Comment by agilgur5** [comment] 2023-07-19 05:49
A [test](https://github.com/agilgur5/mst-persist/blob/94422793d11fa3aacb47fe6b30f60c69dcea0441/test/index.spec.ts) with arrays would also help validate this scenario. In general, tests with more complicated shapes would be helpful

**Comment by agilgur5** [comment] 2023-07-19 07:03
Added an array test in #38 which passes successfully, so I can't reproduce this. I'm gonna guess this might have been due to lack of merge strategies, i.e. #5

**Closed as completed by agilgur5** 2023-07-19 07:03 UTC
Labels: solution: duplicate, solution: can't repro, kind: support, solution: needs test
